name: Build and Deploy

on:
  push:
    branches:
      - main  # Passe den Branch an, den du verwenden möchtest
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set Timestamp Variable
        id: timestamp
        run: echo "TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Passe die Node.js-Version an dein Projekt an

      - name: Inject Environment Variables
        run: |
          echo "CONTENTFUL_SPACE_ID=${{ secrets.CONTENTFUL_SPACE_ID }}" >> .env
          echo "CONTENTFUL_DELIVERY_TOKEN=${{ secrets.CONTENTFUL_DELIVERY_TOKEN }}" >> .env

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: create directory
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22  # Passe den Port an, falls er nicht 22 ist
          script: |
            # Navigiere zu deinem Zielordner und entferne alte Dateien
            cd ~/www.deter-consulting.de/
            mkdir ${{ env.TIMESTAMP }}

      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
          src: ./dist/*
          host: ${{ secrets.SERVER_HOST }}
          user: ${{ secrets.SERVER_USER }}
          port: 22  # Passe den Port an, falls er nicht 22 ist
          remote: ~/www.deter-consulting.de/${{ env.TIMESTAMP }}
          key: ${{secrets.SERVER_SSH_KEY}}

      - name: Set new symlink
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22  # Passe den Port an, falls er nicht 22 ist
          script: |
            # Navigiere zu deinem Zielordner und entferne alte Dateien
            cd ~/www.deter-consulting.de/
            rm current && ln -s ${{ env.TIMESTAMP }} current
